import os
import subprocess
import json
import tempfile
import uuid
import re
import asyncio
from pathlib import Path
from typing import Dict, Optional
from app.utils.logger import logger
from app.models.download import VideoInfo
from app.config.settings import settings
from app.exceptions import (
    InvalidVideoURLError,
    VideoNotFoundError,
    VideoDownloadError
)
from app.monitoring.metrics import metrics_tracker
from app.services.cookie_refresh_service import cookie_refresh_service


class YouTubeService:
    def __init__(self):
        self.download_dir = Path("downloads")
        self.download_dir.mkdir(exist_ok=True)

        # Get yt-dlp path (use local venv version by default)
        self.yt_dlp_path = os.getenv('YT_DLP_PATH', 'yt-dlp')

        # Get ffmpeg path (use local bin version if available)
        self.ffmpeg_path = os.getenv('FFMPEG_PATH', 'ffmpeg')
        self.ffprobe_path = os.getenv('FFPROBE_PATH', 'ffprobe')

        # Optional cookies file for YouTube authentication (to avoid bot detection)
        self.cookies_file = os.getenv('YT_DLP_COOKIES_FILE')

        # Optional proxy (helps bypass IP-based bot detection on cloud servers)
        self.proxy = os.getenv('YT_DLP_PROXY')

    def _extract_video_id(self, url: str) -> str:
        """Extract video ID from YouTube URL"""
        patterns = [
            r'(?:youtube\.com\/(?:shorts\/|watch\?v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})',
            r'youtube\.com\/embed\/([a-zA-Z0-9_-]{11})',
            r'youtube\.com\/v\/([a-zA-Z0-9_-]{11})'
        ]

        for pattern in patterns:
            match = re.search(pattern, url)
            if match:
                return match.group(1)

        raise InvalidVideoURLError(url)

    def _create_temp_cookies_file(self, cookies: Dict[str, str]) -> str:
        """Create temporary cookies file in Netscape format from dict"""
        try:
            fd, temp_path = tempfile.mkstemp(suffix='.txt', prefix='yt_cookies_')
            with os.fdopen(fd, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file is generated by yt-dlp.  Do not edit.\n\n")
                for name, value in cookies.items():
                    f.write(f".youtube.com\tTRUE\t/\tTRUE\t0\t{name}\t{value}\n")
            logger.info(f"Created temporary cookies file with {len(cookies)} cookies")
            return temp_path
        except Exception as e:
            logger.error(f"Error creating temp cookies file: {e}")
            return None

    def _handle_cookie_error(self, error_message: str, video_id: str):
        """Handle cookie-related errors by triggering cookie refresh"""
        # Check if cookies file is missing
        if not cookie_refresh_service.check_cookies_file_exists():
            logger.warning(f"⚠️ Cookies file missing for video {video_id}")
            cookie_refresh_service.trigger_cookie_refresh(reason="missing_cookies")
            return

        # Check if error indicates bot detection or authentication issues
        if cookie_refresh_service.is_cookie_refresh_needed(error_message):
            logger.warning(f"🔄 Cookie refresh needed for video {video_id}: {error_message[:100]}")
            cookie_refresh_service.trigger_cookie_refresh(reason="bot_detection")
        else:
            logger.debug(f"Error does not require cookie refresh: {error_message[:100]}")

    async def get_video_info(self, url: str, cookies: Optional[Dict[str, str]] = None) -> VideoInfo:
        """Get video information using yt-dlp"""
        with metrics_tracker.track_youtube_api('get_video_info'):
            video_id = self._extract_video_id(url)
            temp_cookies_file = None

            try:
                cmd = [self.yt_dlp_path, '--dump-json', '--no-playlist', url]

                # Enable Node.js runtime (required for 2026 YouTube n-challenge)
                cmd.extend(["--js-runtimes", "node"])
                cmd.extend(["--remote-components", "ejs:github"])

                if self.ffmpeg_path != 'ffmpeg':
                    cmd.extend(['--ffmpeg-location', os.path.dirname(self.ffmpeg_path)])

                # Check if server cookies file is missing - trigger refresh
                if self.cookies_file and not os.path.exists(self.cookies_file):
                    logger.warning(f"⚠️ Cookies file missing: {self.cookies_file}")
                    cookie_refresh_service.trigger_cookie_refresh(reason="missing_cookies")
                    # Don't use user-provided cookies as fallback - wait for refresh
                    use_cookies_file = None
                # Server cookies exist - use them
                elif self.cookies_file and os.path.exists(self.cookies_file):
                    use_cookies_file = self.cookies_file
                # No server cookies configured, user provided cookies - use them
                elif cookies:
                    temp_cookies_file = self._create_temp_cookies_file(cookies)
                    use_cookies_file = temp_cookies_file
                else:
                    use_cookies_file = None

                if use_cookies_file:
                    cmd.extend(['--cookies', use_cookies_file])
                else:
                    cmd.extend(['--extractor-args', 'youtube:player_client=android,ios'])

                if self.proxy:
                    cmd.extend(['--proxy', self.proxy])

                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    check=False,
                    timeout=settings.YTDLP_INFO_TIMEOUT
                )

                if result.returncode != 0:
                    stderr = result.stderr if result.stderr else ""

                    # Check for cookie-related errors and trigger refresh if needed
                    self._handle_cookie_error(stderr, video_id)

                    # Parse yt-dlp errors
                    if "Video unavailable" in stderr:
                        raise VideoNotFoundError(video_id, "Video is unavailable")
                    elif "Private video" in stderr:
                        raise VideoNotFoundError(video_id, "Video is private")
                    elif "This video is no longer available" in stderr:
                        raise VideoNotFoundError(video_id, "Video has been removed")
                    elif "video doesn't exist" in stderr.lower():
                        raise VideoNotFoundError(video_id, "Video does not exist")
                    else:
                        raise VideoDownloadError(video_id, stderr)

                info = json.loads(result.stdout)

                return VideoInfo(
                    id=info['id'],
                    title=info['title'],
                    thumbnail=info['thumbnail'],
                    duration=info['duration'],
                    quality=f"{info.get('height', 'N/A')}p" if info.get('height') else None,
                    file_size=self._format_file_size(info.get('filesize')) if info.get('filesize') else None
                )

            except subprocess.TimeoutExpired:
                raise VideoDownloadError(video_id, f"Request timed out after {settings.YTDLP_INFO_TIMEOUT} seconds")
            except FileNotFoundError:
                raise VideoDownloadError(video_id, "yt-dlp binary not found")
            except json.JSONDecodeError as e:
                raise VideoDownloadError(video_id, f"Invalid JSON response from yt-dlp: {str(e)}")
            except (InvalidVideoURLError, VideoNotFoundError, VideoDownloadError):
                raise
            except Exception as e:
                logger.error(f"Error fetching video info: {e}")
                raise VideoDownloadError(video_id, str(e))
            finally:
                if temp_cookies_file and os.path.exists(temp_cookies_file):
                    os.remove(temp_cookies_file)

    def download_video_sync(self, url: str, video_id: str, progress_callback=None, cookies: Optional[Dict[str, str]] = None) -> str:
        """Download video using yt-dlp with real-time progress tracking (sync version)"""
        with metrics_tracker.track_youtube_api('download_video'):
            temp_cookies_file = None
            try:
                file_name = f"{video_id}_{uuid.uuid4().hex[:8]}.mp4"
                output_path = self.download_dir / file_name

                cmd = [
                    self.yt_dlp_path,
                    '--js-runtimes', 'node',
                    '--remote-components', 'ejs:github',
                    '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
                    '--merge-output-format', 'mp4',
                    '--newline',
                    '-o', str(output_path),
                    url
                ]

                if self.ffmpeg_path != 'ffmpeg':
                    cmd.extend(['--ffmpeg-location', os.path.dirname(self.ffmpeg_path)])

                # Check if server cookies file is missing - trigger refresh
                if self.cookies_file and not os.path.exists(self.cookies_file):
                    logger.warning(f"⚠️ Cookies file missing: {self.cookies_file}")
                    cookie_refresh_service.trigger_cookie_refresh(reason="missing_cookies")
                    # Don't use user-provided cookies as fallback - wait for refresh
                    use_cookies_file = None
                # Server cookies exist - use them
                elif self.cookies_file and os.path.exists(self.cookies_file):
                    use_cookies_file = self.cookies_file
                # No server cookies configured, user provided cookies - use them
                elif cookies:
                    temp_cookies_file = self._create_temp_cookies_file(cookies)
                    use_cookies_file = temp_cookies_file
                else:
                    use_cookies_file = None

                if use_cookies_file:
                    cmd.extend(['--cookies', use_cookies_file])
                    cmd.extend(['--extractor-args', 'youtube:player_client=web'])
                else:
                    cmd.extend(['--extractor-args', 'youtube:player_client=android,ios'])

                if self.proxy:
                    cmd.extend(['--proxy', self.proxy])

                process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1,
                    universal_newlines=True
                )

                logger.info(f"Starting download for {video_id}")
                last_progress = 0
                stderr_output = []

                for line in process.stdout:
                    line = line.strip()
                    stderr_output.append(line)

                    if progress_callback:
                        if '[download]' in line and '%' in line:
                            match = re.search(r'(\d+\.?\d*)%', line)
                            if match:
                                percentage = float(match.group(1))
                                scaled_progress = int(20 + (percentage * 0.6))
                                if scaled_progress > last_progress:
                                    progress_callback(scaled_progress)
                                    last_progress = scaled_progress
                        elif '[Merger]' in line or 'Merging formats' in line:
                            progress_callback(85)

                process.wait()
                if process.returncode != 0:
                    stderr = "\n".join(stderr_output)

                    # Check for cookie-related errors and trigger refresh if needed
                    self._handle_cookie_error(stderr, video_id)

                    raise VideoDownloadError(video_id, stderr)

                return str(output_path)

            except subprocess.TimeoutExpired:
                raise VideoDownloadError(video_id, f"Download timed out after {settings.YTDLP_DOWNLOAD_TIMEOUT} seconds")
            except FileNotFoundError:
                raise VideoDownloadError(video_id, "yt-dlp binary not found")
            except VideoDownloadError:
                raise
            except Exception as e:
                logger.error(f"Error downloading video: {e}")
                raise VideoDownloadError(video_id, str(e))
            finally:
                if temp_cookies_file and os.path.exists(temp_cookies_file):
                    os.remove(temp_cookies_file)

    async def download_video(self, url: str, video_id: str, progress_callback=None) -> str:
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self.download_video_sync, url, video_id, progress_callback)

    async def delete_local_file(self, file_path: str):
        try:
            os.remove(file_path)
            logger.info(f"Local file deleted: {file_path}")
        except Exception as e:
            logger.error(f"Error deleting local file: {e}")

    def _format_file_size(self, bytes_val: int) -> str:
        if not bytes_val: return "0 Bytes"
        k = 1024
        sizes = ['Bytes', 'KB', 'MB', 'GB']
        i = 0
        size = float(bytes_val)
        while size >= k and i < len(sizes) - 1:
            size /= k
            i += 1
        return f"{round(size, 2)} {sizes[i]}"

youtube_service = YouTubeService()
